[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "RRReddit"
authors = [{name = "Bowman", email = "vlg007@latech.edu"}]
dynamic = ["version", "description"]
